export const CardImages = {
        herc7: require('../components/cards/Fronts/herc/herc7.png'),
        herc8: require('../components/cards/Fronts/herc/herc8.png'),
        herc9: require('../components/cards/Fronts/herc/herc9.png'),
        herc10: require('../components/cards/Fronts/herc/herc10.png'),
        hercAs: require('../components/cards/Fronts/herc/hercAs.png'),
        hercBaba: require('../components/cards/Fronts/herc/hercBaba.png'),
        hercDecko: require('../components/cards/Fronts/herc/hercDecko.png'),
        hercKralj: require('../components/cards/Fronts/herc/hercKralj.png'),

        kara7: require('../components/cards/Fronts/kara/kara7.png'),
        kara8: require('../components/cards/Fronts/kara/kara8.png'),
        kara9: require('../components/cards/Fronts/kara/kara9.png'),
        kara10: require('../components/cards/Fronts/kara/kara10.png'),
        karaAs: require('../components/cards/Fronts/kara/karaAs.png'),
        karaBaba: require('../components/cards/Fronts/kara/karaBaba.png'),
        karaDecko: require('../components/cards/Fronts/kara/karaDecko.png'),
        karaKralj: require('../components/cards/Fronts/kara/karaKralj.png'),

        pik7: require('../components/cards/Fronts/pik/pik7.png'),
        pik8: require('../components/cards/Fronts/pik/pik8.png'),
        pik9: require('../components/cards/Fronts/pik/pik9.png'),
        pik10: require('../components/cards/Fronts/pik/pik10.png'),
        pikAs: require('../components/cards/Fronts/pik/pikAs.png'),
        pikBaba: require('../components/cards/Fronts/pik/pikBaba.png'),
        pikDecko: require('../components/cards/Fronts/pik/pikDecko.png'),
        pikKralj: require('../components/cards/Fronts/pik/pikKralj.png'),

        tref7: require('../components/cards/Fronts/tref/tref7.png'),
        tref8: require('../components/cards/Fronts/tref/tref8.png'),
        tref9: require('../components/cards/Fronts/tref/tref9.png'),
        tref10: require('../components/cards/Fronts/tref/tref10.png'),
        trefAs: require('../components/cards/Fronts/tref/trefAs.png'),
        trefBaba: require('../components/cards/Fronts/tref/trefBaba.png'),
        trefDecko: require('../components/cards/Fronts/tref/trefDecko.png'),
        trefKralj: require('../components/cards/Fronts/tref/trefKralj.png'),

        cardBack: require('../components/cards/Backs/CardBack1.png'),
    };