name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - lukasDev

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        env:
          QODANA_TOKEN: ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoiSmdKTWwiLCJvcmdhbml6YXRpb24iOiJBUk5XayIsInRva2VuIjoid3dPNTcifQ.Kq7Ca2j0BdD5s9zc6-om7Y35iwyJMrz_hQ_Vo_oG5uI }}