import { StyleSheet } from 'react-native';

const CARD_WIDTH = 60;
const CARD_HEIGHT = 100;
const STACK_OFFSET = 0;

const styles = StyleSheet.create({
  //HomeScreen stilovi ----------------------------
  profileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: 10,
    left: 10,
  },
  image: {
    width: 40,
    height: 40,
    marginRight: 8,
  },
  profileText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  headerContainer: {
    marginTop: 40,
    alignItems: 'center',
    marginBottom: 40,
  },
  headerText: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  buttonsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    height: 35,
    backgroundColor: '#daa520',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginVertical: 5,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  profileModalContent: {
    backgroundColor: '#696969',
    borderRadius: 16,
    padding: 24,
    width: '60%',
    alignItems: 'center',
  },
  profileModalImage: {
    width: 60,
    height: 60,
    marginBottom: 16,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    width: '100%',
    justifyContent: 'space-between',
  },
  changeButton: {
    backgroundColor: '#444',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginLeft: 12,
  },
  changeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  profileModalText: {
    fontSize: 18,
    color: '#ffffff',
    flex: 1,
  },
  friendsModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  friendsModalContent: {
    backgroundColor: '#222',
    borderRadius: 16,
    width: '80%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  closeFriendsButton: {
    fontSize: 20,
    color: '#fff',
    padding: 4,
    marginRight: 4,
    marginTop: 2,
  },
  friendsModalTabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    width: '100%',
  },
  friendsModalTab: {
    flex: 1,
    paddingVertical: 10,
    backgroundColor: '#444',
    borderRadius: 8,
    marginHorizontal: 4,
    alignItems: 'center',
  },
  friendsModalTabText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 16,
    marginTop: 1,
    marginBottom: 8,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#fff',
    color: '#222',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginRight: 10,
    fontSize: 16,
    height: 40,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  searchButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 18,
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
  },
  searchButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  searchResultsContainer: {
    maxHeight: 200,
    width: '100%',
    marginBottom: 10,
  },
  searchResultItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  searchResultItem2: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#333',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  searchResultText: {
    color: '#fff',
    fontSize: 15,
  },
  searchResultText2: {
    color: '#fff',
    fontSize: 15,
    width: 350,
  },
  sendRequestButton: {
    backgroundColor: '#2196F3',
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  sendRequestButtonText: {
    color: '#fff',
    fontSize: 14,
  },
  inventoryModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inventoryModalContent: {
    backgroundColor: '#222',
    borderRadius: 16,
    padding: 15,
    width: 700,
    alignItems: 'flex-start',
  },
  inventoryHeader: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    marginBottom: 5,
    marginLeft: 6,
  },
  inventorySection: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    marginTop: 2,
    marginBottom: 2,
    marginLeft: 6,
    alignSelf: 'flex-start',
  },
  inventoryImageRow: {
    flexDirection: 'row',
    marginBottom: 1,
    marginLeft: 6,
  },
  inventoryImagePlaceholder: {
    width: 60,
    height: 95,
    backgroundColor: '#444',
    borderRadius: 8,
    marginRight: 18,
    borderWidth: 3,
    borderColor: '#fff',
  },
  inventoryCloseButton: {
    backgroundColor: '#ff4d4d',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 32,
    alignSelf: 'center',
    marginTop: 8,
  },
  inventoryCloseButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 10,
  },
  profileModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '70%',
    marginTop: 24,
  },
  profileScrollContainer: {
    alignItems: 'center',
    width: '100%',
  },
  profileButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
    marginBottom: 10,
  },
  profileModalButton: {
    backgroundColor: '#444',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  profileModalButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  changeModalContent: {
    backgroundColor: '#222',
    borderRadius: 16,
    padding: 24,
    width: '80%',
    alignItems: 'center',
  },
  changeModalTitle: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    marginBottom: 16,
  },
  changeModalInput: {
    backgroundColor: '#444',
    borderRadius: 8,
    color: '#fff',
    fontSize: 16,
    padding: 10,
    width: '100%',
    marginBottom: 8,
  },
  saveButton: {
    backgroundColor: '#4caf50',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
    marginRight: 10,
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  signOutButton: {
    backgroundColor: '#444',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
    marginLeft: 8,
    flex: 1,
    alignItems: 'center',
  },
  signOutButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  closeButtonTutorial: {
    backgroundColor: '#ff4d4d',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 15,
    flex: 1,
    alignItems: 'center',
    marginLeft: 8,
  },
  closeButtonTextTutorial: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  closeButton: {
    backgroundColor: '#ff4d4d',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 24,
    flex: 1,
    alignItems: 'center',
    marginLeft: 8,
  },
  closeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#696969',
    borderRadius: 16,
    padding: 24,
    width: '80%',
    height:'90%',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#ffffff',
    textAlign: 'center',
  },
  modalText: {
    fontSize: 16,
    color: '#ffffff',
    marginBottom: 20,
    textAlign: 'left',
  },
  languageRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
    marginBottom: 8,
  },
  languageButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#eee',
    borderRadius: 8,
    alignSelf: 'flex-end',
  },
  languageButtonText: {
    color: '#333',
    fontWeight: 'bold',
  },
  dropdown: {
    position: 'absolute',
    top: 40,
    right: 24,
    backgroundColor: '#fff',
    borderRadius: 8,
    elevation: 5,
    zIndex: 10,
    width: 120,
  },
  dropdownItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  dropdownText: {
    color: '#333',
    fontSize: 16,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  quitButton: {
    width: 80,
    height: 35,
    backgroundColor: '#ff4d4d',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 30,
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  quitButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  createLobbyModalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  createLobbyModalContent: {
    backgroundColor: '#2a2a2a',
    margin: 20,
    padding: 20,
    borderRadius: 10,
  },
  createLobbyModalTitle: {
    fontSize: 20,
    color: 'white',
    marginBottom: 15,
    textAlign: 'center',
  },
  createLobbyModalInput: {
    backgroundColor: '#333',
    color: 'white',
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
  },
  createLobbyModalCheckbox: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 5,
    marginBottom: 10,
  },
  createLobbyModalCheckboxChecked: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  createLobbyModalCheckboxText: {
    color: 'white',
    textAlign: 'center',
  },
  createLobbyModalCreateButton: {
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 5,
    marginTop: 10,
  },
  createLobbyModalCancelButton: {
    backgroundColor: '#f44336',
    padding: 15,
    borderRadius: 5,
    marginTop: 10,
  },
  createLobbyModalButtonText: {
    color: 'white',
    textAlign: 'center',
  },
  //HomeScreen stilovi ----------------------------

  //SignInScreen stilovi---------------------------
  container: {
    padding: 24,
    flex: 1,
  },
  header: {
    padding: 20,
    marginTop: 150,
  },
  loginText: {
    fontSize: 27,
    fontWeight: '700',
    marginBottom: 6,
    textAlign: 'center',
    color: '#ffffff',
  },
  form: {
    marginTop: 10,
    flex: 1,
  },
  input: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 8,
    color: '#ffffff',
  },
  inputControl: {
    height: 44,
    backgroundColor: '#696969',
    paddingHorizontal: 16,
    borderRadius: 12,
    fontSize: 15,
    fontWeight: '500',
    color: '#222',
  },
  formFooter: {
    fontSize: 17,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 0.15,
  },
  btn: {
    backgroundColor: '#696969',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#696969',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 20,
    marginTop: 10,
  },
  btnText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
  },
  //SignInScreen stilovi-------------------

  //SignUpScreen stilovi-------------------
  containerSignUp: { padding: 24, flex: 1 },
  headerSignUp: { padding: 20, marginTop: 100 },
  loginTextSignUp: {
    fontSize: 27,
    fontWeight: '700',
    marginBottom: 6,
    textAlign: 'center',
    color: '#ffffff',
  },
  formSignUp: { marginTop: 10, flex: 1 },
  inputSignUp: { marginBottom: 20 },
  inputLabelSignUp: {
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 8,
    color: '#ffffff',
  },
  inputControlSignUp: {
    height: 44,
    backgroundColor: '#696969',
    paddingHorizontal: 16,
    borderRadius: 12,
    fontSize: 15,
    fontWeight: '500',
    color: '#ffffff',
  },
  formAction: { marginTop: 20 },
  btnSignUp: {
    backgroundColor: '#696969',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#696969',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  formFooterSignUp: {
    fontSize: 17,
    fontWeight: '600',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 0.15,
    marginTop: 10,
  },
  btnTextSignUp: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
  },
  //SignUpScreen stilovi---------------------

  //LobbyDetails stilovi---------------------
  lobbyDetailsContainer: {
    flex: 1,
    backgroundColor: '#111',
    justifyContent: 'center',
    alignItems: 'center',
  },
  passwordInput: {
    margin: 10,
    padding: 8,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    backgroundColor: '#fff',
  },
  lobbyDetailsBox: {
    backgroundColor: '#181828',
    borderRadius: 18,
    padding: 24,
    width: 500,
    alignItems: 'center',
    elevation: 8,
  },
  lobbyDetailsTeamsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    justifyContent: 'center',
  },
  lobbyDetailsTeamColumn: {
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 120,
  },
  lobbyDetailsPlayerBox: {
    backgroundColor: '#241c2b',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 18,
    marginVertical: 8,
    width: 200,
  },
  lobbyDetailsPlayerIcon: {
    fontSize: 24,
    marginRight: 12,
    color: '#fff',
  },
  lobbyDetailsPlayerName: {
    color: '#fff',
    fontSize: 16,
  },
  lobbyDetailsVS: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 28,
    marginHorizontal: 18,
  },
  lobbyDetailsBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    width: '100%',
    justifyContent: 'space-between',
  },
  lobbyDetailsLeaveButton: {
    backgroundColor: '#333',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  lobbyDetailsLeaveButtonText: {
    color: '#fff',
    fontSize: 13,
  },
  lobbyDetailsStartButton: {
    backgroundColor: '#b03e3e',
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 32,
    marginHorizontal: 10,
    marginRight: 15,
  },
  lobbyDetailsStartButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  lobbyDetailsMessage: {
    color: '#f39c12',
    fontWeight: 'bold',
    fontSize: 16,
    marginTop: 12,
    textAlign: 'center',
    backgroundColor: '#333',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  lobbyDetailsCodeBox: {
    backgroundColor: '#222',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  lobbyDetailsCodeText: {
    color: '#fff',
    fontSize: 13,
  },
  lobbyDetailsIdBox: {
    backgroundColor: '#222',
    borderRadius: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  lobbyDetailsIdText: {
    color: '#fff',
    fontSize: 13,
  },
  //LobbyDetails stilovi----------

  //LobbyList stilovi---------
  lobbycontainer: {
    flex: 1,
    padding: 20
  },
  lobbyItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderColor: '#444'
  },
  lobbyName: {
    fontSize: 18,
    fontWeight: 'bold'
  },
  createButtonlobby: {
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 5,
    marginTop: 10
  },
  buttonTextlobby: {
    color: 'white',
    textAlign: 'center'
  },
  //LobbyList stilovi---------

  //MatchScreen stilovi-----------
  matchcontainer: {
    backgroundColor: '#101020',
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  turnIndicatorContainer: {
    position: 'absolute',
    top: 16,
    left: 16,
    zIndex: 100,
  },
  trumpIndicator: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 100,
  },
  turnIndicatorText: {
    color: '#00ff88',
    fontSize: 18,
    fontWeight: 'bold',
  },
  scoreboard: {
    position: 'absolute',
    top: 20, 
    alignSelf: 'flex-end',
  },
  teamLabel: {
    fontWeight: 'bold',
    color: '#fff',
    fontSize: 16,
    marginRight: 120,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 140,
    marginTop: 4,
  },
  playerBottom: {
    position: 'absolute',
    bottom: 110,
    left: '50%',
    transform: [{ translateX: -50 }],
    alignItems: 'center',
  },
  reconnectingBanner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#ffbb00',
    padding: 8,
    alignItems: 'center',
    zIndex: 100,
  },
  bannerText: {
    color: '#222',
    fontSize: 16,
    fontWeight: 'bold',
  },
  errorBanner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#ff4444',
    padding: 8,
    alignItems: 'center',
    zIndex: 100,
  },
  errorText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  topPlayer: {
    position: 'absolute',
    top: 16,
    left: '50%',
    transform: [{ translateX: -50 }],
    alignItems: 'center',
  },
  leftPlayer: {
    position: 'absolute',
    top: '50%',
    left: 16,
    transform: [{ translateY: -25 }],
    alignItems: 'center',
  },
  rightPlayer: {
    position: 'absolute',
    top: '50%',
    right: 16,
    transform: [{ translateY: -25 }],
    alignItems: 'center',
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#444',
  },
  username: {
    color: 'white',
    fontSize: 16,
    marginTop: 4,
  },
  playArea: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -40 }, { translateY: -60 }],
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 120,
    zIndex: 10,
  },
  card: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
  },
  handRow: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    bottom: 16,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    zIndex: 20,
    justifyContent: 'space-between',
  },
  playCardButton: {
    backgroundColor: '#27232a',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    top: 30,
    marginRight: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  challengeButton: {
    backgroundColor: '#27232a',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    top: 30,
    marginLeft: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  handContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    top: 25,
    height: 140,
    flex: 1,
    justifyContent: 'center',
  },
  cardContainer: {
    position: 'relative',
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    marginLeft: 5,
    marginRight: 5,
  },
  handCard: {
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    marginLeft: -STACK_OFFSET,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  selectedCard: {
    borderColor: '#00ff88',
  },
  actions: {
    position: 'absolute',
    bottom: 180,
    left: 0,
    right: 0,
    flexDirection: 'column',
    alignItems: 'center',
    zIndex: 30,
  },
  buttonTextAction: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  bidButtons: {
    flexDirection: 'row',
    marginTop: 16,
  },
  trumpIcon: {
    width: 40,
    height: 50,
    resizeMode: 'contain',
  },
  bidButton: {
    backgroundColor: '#27232a',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    marginHorizontal: 8,
  },
  //MatchScreen stilovi-------------
});

export default styles;
